import { test, expect } from '@playwright/test';
import { buildUser } from '../../fixtures/data-factory';

// jsonplaceholder accepts writes and echoes them back with a fresh id
// but doesn't persist. Fine for contract testing — we're checking the
// REST surface, not database state.

test.describe('jsonplaceholder — posts (CRUD)', () => {
  test('POST /posts creates a post', async ({ request }) => {
    const user = buildUser();
    const payload = {
      title: `Portfolio test — ${user.username}`,
      body: 'Generated by the qa-ai-automation-framework test suite.',
      userId: 1,
    };

    const res = await request.post('/posts', { data: payload });
    expect(res.status()).toBe(201);

    const body = await res.json();
    expect(body).toMatchObject({
      ...payload,
      id: expect.any(Number),
    });
  });

  test('PUT /posts/:id replaces a post', async ({ request }) => {
    const payload = {
      id: 1,
      title: 'Replaced title',
      body: 'Replaced body',
      userId: 1,
    };

    const res = await request.put('/posts/1', { data: payload });
    expect(res.status()).toBe(200);
    expect(await res.json()).toMatchObject(payload);
  });

  test('PATCH /posts/:id partially updates a post', async ({ request }) => {
    const payload = { title: 'Patched title only' };

    const res = await request.patch('/posts/1', { data: payload });
    expect(res.status()).toBe(200);

    const body = await res.json();
    expect(body).toMatchObject({ id: 1, title: payload.title });
    // Untouched fields remain present — losing them would be a regression.
    expect(body.body).toBeDefined();
    expect(body.userId).toBeDefined();
  });

  test('DELETE /posts/:id returns 200 with an empty payload', async ({
    request,
  }) => {
    const res = await request.delete('/posts/1');
    expect(res.status()).toBe(200);
    expect(await res.json()).toEqual({});
  });
});
