import { test, expect } from '@playwright/test';
import { buildUser } from '../../fixtures/data-factory';
import { PostSchema, PostEchoSchema } from './schemas';

// jsonplaceholder accepts writes and echoes them back with a fresh id
// but doesn't persist. Fine for contract testing — we're checking the
// REST surface, not database state. Zod parse() on every response so
// shape drift fails with a real diagnostic.

test.describe('jsonplaceholder — posts (CRUD)', () => {
  test('POST /posts creates a post', async ({ request }) => {
    const user = buildUser();
    const payload = {
      title: `Portfolio test — ${user.username}`,
      body: 'Generated by the qa-ai-automation-framework test suite.',
      userId: 1,
    };

    const res = await request.post('/posts', { data: payload });
    expect(res.status()).toBe(201);

    const created = PostSchema.parse(await res.json());
    expect(created).toMatchObject(payload);
  });

  test('PUT /posts/:id replaces a post', async ({ request }) => {
    const payload = {
      id: 1,
      title: 'Replaced title',
      body: 'Replaced body',
      userId: 1,
    };

    const res = await request.put('/posts/1', { data: payload });
    expect(res.status()).toBe(200);

    const replaced = PostSchema.parse(await res.json());
    expect(replaced).toMatchObject(payload);
  });

  test('PATCH /posts/:id partially updates a post', async ({ request }) => {
    const payload = { title: 'Patched title only' };

    const res = await request.patch('/posts/1', { data: payload });
    expect(res.status()).toBe(200);

    // PostEchoSchema (partial) because PATCH responses still include
    // the untouched fields — but we validate that separately below so
    // losing those untouched fields would be a real regression.
    const patched = PostEchoSchema.parse(await res.json());
    expect(patched.id).toBe(1);
    expect(patched.title).toBe(payload.title);
    expect(patched.body).toBeDefined();
    expect(patched.userId).toBeDefined();
  });

  test('DELETE /posts/:id returns 200 with an empty payload', async ({
    request,
  }) => {
    const res = await request.delete('/posts/1');
    expect(res.status()).toBe(200);
    expect(await res.json()).toEqual({});
  });
});
