/**
 * Automation router — writes generated feature + steps files, spawns Playwright,
 * streams the live log back over Server-Sent Events, and reports per-scenario results.
 *
 * POST /automation/run
 *   Body: { ticketId, platform, testCases: [{id,name,steps,expected,type}] }
 *   Returns: SSE stream of events:
 *     event: log      data: { line, stream: "stdout"|"stderr" }
 *     event: progress data: { scenario, status: "running"|"pass"|"fail" }
 *     event: result   data: { ticketId, passed, failed, reportPath, tcResults: [...] }
 *     event: error    data: { message }
 *     event: done     data: { ok, elapsedSec }
 */

import { Router, Request, Response } from 'express';
import { spawn, ChildProcessWithoutNullStreams } from 'child_process';
import fs from 'fs';
import path from 'path';
import {
  generateStepBodies,
  isLLMConfigured,
  StepToGenerate,
} from './step-generator';

export const automationRouter = Router();

const FRAMEWORK_ROOT = path.resolve(__dirname, '..');
const FEATURES_DIR = path.join(FRAMEWORK_ROOT, 'features', 'generated');
const STEPS_DIR = path.join(FRAMEWORK_ROOT, 'steps', 'generated');

interface TestCase {
  id: string;
  name: string;
  steps: string;
  expected: string;
  type?: string;
}

interface RunBody {
  ticketId: string;
  platform?: string;
  testCases: TestCase[];
  headed?: boolean;
  /** The target the tests run against.
   *  - Web/API: an http(s) URL (sets BASE_URL env for Playwright)
   *  - iOS/Android: if ends in .apk/.app → logged as unsupported (needs Appium);
   *    otherwise treated as a mobile web URL. */
  baseUrl?: string;
  /** If true (default), the server launches a browser, scans the target page,
   *  and uses an LLM to write the step bodies before running tests. When false,
   *  only skeleton stubs are written and every test fails with "not implemented". */
  autoImplement?: boolean;
}

function sanitizeTag(s: string): string {
  return (s || 'ticket')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function sanitizeGherkin(s: string): string {
  return (s || '')
    .replace(/[\r\n]+/g, ' ')
    .replace(/\|/g, '-')
    .trim();
}

/** Build the .feature file contents from a list of TCs.
 *  Each scenario name is prefixed with [TC-XX] so Playwright's list reporter
 *  echoes the TC ID back — the frontend parses that to flip the right row
 *  without fuzzy substring matching. */
function buildFeatureFile(ticketId: string, testCases: TestCase[]): string {
  const tag = sanitizeTag(ticketId);
  const scenarios = testCases
    .map((tc) => {
      const stepParts = (tc.steps || '')
        .split(' > ')
        .map((s) => s.trim())
        .filter(Boolean);
      const given = stepParts[0]
        ? `Given ${sanitizeGherkin(stepParts[0])}`
        : 'Given the test setup is ready';
      const whens = stepParts
        .slice(1)
        .map((s) => `    When ${sanitizeGherkin(s)}`);
      const then = `    Then ${sanitizeGherkin(tc.expected) || 'the expected outcome is observed'}`;
      const typeTag = tc.type ? ' @' + tc.type : '';
      return `  @generated @${tag}${typeTag}
  Scenario: [${tc.id}] ${sanitizeGherkin(tc.name)}
    ${given}
${whens.join('\n')}
${then}`;
    })
    .join('\n\n');

  return `# Auto-generated by QA Agent on ${new Date().toISOString()}
# Ticket: ${ticketId}

Feature: ${ticketId} — agent-generated verification scenarios

${scenarios}
`;
}

/** Collect the unique step phrases from a list of TCs.
 *  Same logic as the old buildStepsFile's registry but reusable standalone. */
function collectSteps(
  testCases: TestCase[],
): Array<{ keyword: 'Given' | 'When' | 'Then'; phrase: string }> {
  const registry = new Map<
    string,
    { keyword: 'Given' | 'When' | 'Then'; phrase: string }
  >();
  testCases.forEach((tc) => {
    const parts = (tc.steps || '')
      .split(' > ')
      .map((s) => s.trim())
      .filter(Boolean);
    parts.forEach((s, i) => {
      const kw: 'Given' | 'When' = i === 0 ? 'Given' : 'When';
      const key = kw + '|' + s.toLowerCase();
      if (!registry.has(key))
        registry.set(key, { keyword: kw, phrase: sanitizeGherkin(s) });
    });
    const expKey = 'Then|' + (tc.expected || '').toLowerCase();
    if (!registry.has(expKey)) {
      registry.set(expKey, {
        keyword: 'Then',
        phrase:
          sanitizeGherkin(tc.expected) || 'the expected outcome is observed',
      });
    }
  });
  return [...registry.values()];
}

/** Build the .steps.ts file. If `bodies` is provided (keyed by "Keyword|phrase" lowercase),
 *  each step uses its real implementation; otherwise a throw-skeleton is written. */
function buildStepsFile(
  ticketId: string,
  testCases: TestCase[],
  bodies?: Map<string, string>,
): string {
  const steps = collectSteps(testCases);

  const impls = steps
    .map(({ keyword, phrase }) => {
      const safe = phrase.replace(/'/g, "\\'");
      const bodyKey = keyword + '|' + phrase.toLowerCase();
      const realBody = bodies?.get(bodyKey);
      const body = realBody
        ? realBody.replace(/\n/g, '\n  ')
        : `// TODO: implement — generated skeleton for ${ticketId}\n  throw new Error('Step not implemented: ${safe.replace(/'/g, "\\\\'")}');`;
      return `${keyword}('${safe}', async ({ page }) => {\n  ${body}\n});`;
    })
    .join('\n\n');

  const header = bodies
    ? `/**\n * AI-implemented step definitions for ${ticketId}\n * Generated by QA Agent (with LLM step bodies) on ${new Date().toISOString()}\n *\n * Bodies were generated against the scanned target page. If a step fails with a\n * selector error, the target page may have shifted — re-run Run Automation to\n * regenerate, or hand-edit this file and re-run with "Auto-implement" off.\n */`
    : `/**\n * Auto-generated step skeletons for ${ticketId}\n * Generated by QA Agent on ${new Date().toISOString()}\n *\n * Every step below throws until you implement it or re-run with\n * "Auto-implement steps" enabled.\n */`;

  return `${header}\nimport { expect } from '@playwright/test';\nimport { Given, When, Then } from '../../fixtures';\n\n${impls}\n`;
}

/** Send one SSE event. Flushes immediately. */
function sse(res: Response, event: string, data: unknown): void {
  res.write(`event: ${event}\n`);
  res.write(`data: ${JSON.stringify(data)}\n\n`);
}

/** Parse a line of Playwright test output for scenario status.
 *  Extracts the [TC-XX] prefix we embed in scenario names so the frontend
 *  can flip the right row deterministically. */
function parseProgressLine(
  line: string,
): { scenario?: string; tcId?: string; status?: 'pass' | 'fail' } | null {
  // Playwright list reporter: "  ✓  [bdd:chromium] › features/...feature:XX › [TC-01] Scenario name (42ms)"
  const passMatch = line.match(/✓\s+.*›\s+(.+?)\s+\(\d+(?:\.\d+)?(?:ms|s)\)/);
  if (passMatch) {
    const scenario = passMatch[1].trim();
    const tcIdMatch = scenario.match(/\[([A-Za-z]+-[A-Za-z0-9-]+)\]/);
    return { scenario, tcId: tcIdMatch?.[1], status: 'pass' };
  }
  const failMatch = line.match(
    /[✘×]\s+.*›\s+(.+?)\s+\(\d+(?:\.\d+)?(?:ms|s)\)/,
  );
  if (failMatch) {
    const scenario = failMatch[1].trim();
    const tcIdMatch = scenario.match(/\[([A-Za-z]+-[A-Za-z0-9-]+)\]/);
    return { scenario, tcId: tcIdMatch?.[1], status: 'fail' };
  }
  return null;
}

automationRouter.post('/run', async (req: Request, res: Response) => {
  const body = req.body as RunBody;
  if (
    !body ||
    !body.ticketId ||
    !Array.isArray(body.testCases) ||
    body.testCases.length === 0
  ) {
    res
      .status(400)
      .json({
        error: 'Request must include ticketId and a non-empty testCases array.',
      });
    return;
  }

  // SSE headers — must be set before any writes
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache, no-transform');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('X-Accel-Buffering', 'no');
  res.flushHeaders();

  const tag = sanitizeTag(body.ticketId);
  const featurePath = path.join(FEATURES_DIR, `${tag}.feature`);
  const stepsPath = path.join(STEPS_DIR, `${tag}.steps.ts`);

  try {
    fs.mkdirSync(FEATURES_DIR, { recursive: true });
    fs.mkdirSync(STEPS_DIR, { recursive: true });
    fs.writeFileSync(
      featurePath,
      buildFeatureFile(body.ticketId, body.testCases),
      'utf8',
    );
    sse(res, 'log', {
      stream: 'stdout',
      line: `[qa-agent] Wrote ${featurePath}`,
    });
  } catch (err: any) {
    sse(res, 'error', {
      message: 'Failed to write feature file: ' + err.message,
    });
    sse(res, 'done', { ok: false, elapsedSec: 0 });
    res.end();
    return;
  }

  // ── AI step generation (Phase 3) ──
  // Default: on. Skip only if explicitly disabled OR if no LLM key is configured
  // OR if no baseUrl was supplied (nothing to scan).
  const autoImplement = body.autoImplement !== false;
  const rawTarget = (body.baseUrl || '').trim();
  const canAutoImplement =
    autoImplement &&
    isLLMConfigured() &&
    /^https?:\/\//i.test(rawTarget) &&
    !/\.(apk|ipa|app)(\?|$)/i.test(rawTarget);

  if (canAutoImplement) {
    sse(res, 'phase', { phase: 'generating-steps' });
    sse(res, 'log', {
      stream: 'stdout',
      line: `[qa-agent] ✨ Auto-implementing step bodies against ${rawTarget}`,
    });
    try {
      const steps: StepToGenerate[] = collectSteps(body.testCases);
      const result = await generateStepBodies(rawTarget, steps, {
        onProgress: (msg: string) =>
          sse(res, 'log', { stream: 'stdout', line: `[ai] ${msg}` }),
      });
      sse(res, 'log', {
        stream: 'stdout',
        line: `[qa-agent] Generated ${result.bodies.size} step implementations via ${result.llmProvider} in ${result.elapsedSec}s`,
      });
      fs.writeFileSync(
        stepsPath,
        buildStepsFile(body.ticketId, body.testCases, result.bodies),
        'utf8',
      );
      sse(res, 'log', {
        stream: 'stdout',
        line: `[qa-agent] Wrote ${stepsPath} with AI bodies`,
      });
    } catch (err: any) {
      // If step generation fails, fall back to skeleton stubs so tests still "run" (and fail informatively)
      sse(res, 'log', {
        stream: 'stderr',
        line: `[qa-agent] ⚠ Step generation failed: ${err.message}. Falling back to throw-stubs.`,
      });
      if (!fs.existsSync(stepsPath)) {
        fs.writeFileSync(
          stepsPath,
          buildStepsFile(body.ticketId, body.testCases),
          'utf8',
        );
      }
    }
  } else {
    // Auto-implement disabled / unavailable — write skeleton only if none exists
    if (!fs.existsSync(stepsPath)) {
      fs.writeFileSync(
        stepsPath,
        buildStepsFile(body.ticketId, body.testCases),
        'utf8',
      );
      sse(res, 'log', {
        stream: 'stdout',
        line: `[qa-agent] Wrote skeleton ${stepsPath}`,
      });
    } else {
      sse(res, 'log', {
        stream: 'stdout',
        line: `[qa-agent] Preserving existing ${stepsPath}`,
      });
    }
    // Explain why auto-implement was skipped if it was requested
    if (autoImplement && !isLLMConfigured()) {
      sse(res, 'log', {
        stream: 'stderr',
        line: `[qa-agent] ⚠ Auto-implement requested but no LLM key on server. Set ANTHROPIC_API_KEY or GOOGLE_API_KEY in .env.`,
      });
    } else if (autoImplement && !rawTarget) {
      sse(res, 'log', {
        stream: 'stderr',
        line: `[qa-agent] ⚠ Auto-implement needs a target URL — none provided.`,
      });
    }
  }

  sse(res, 'phase', { phase: 'running-tests' });

  // ── Run `npx bddgen && npx playwright test --project=bdd:chromium --grep "@<tag>"`
  // We chain via `shell: true` so the && works cross-platform, matching the
  // pattern in the framework's existing `npm run test:bdd` script.
  const grep = `@${tag}`;
  const timeoutSec = parseInt(process.env.AUTOMATION_TIMEOUT_SEC || '600', 10);
  const t0 = Date.now();

  const headedFlag = body.headed ? ' --headed' : '';
  const command = `npx bddgen && npx playwright test --project=bdd:chromium${headedFlag} --grep "${grep}" --reporter=list`;

  sse(res, 'log', { stream: 'stdout', line: `[qa-agent] Running: ${command}` });

  // ── Determine what BASE_URL to pass to Playwright (rawTarget already declared above) ──
  const spawnEnv: NodeJS.ProcessEnv = { ...process.env, FORCE_COLOR: '0' };
  const isMobile =
    (body.platform || '').toLowerCase() === 'ios' ||
    (body.platform || '').toLowerCase() === 'android';
  if (rawTarget) {
    if (/\.(apk|ipa|app)(\?|$)/i.test(rawTarget)) {
      sse(res, 'log', {
        stream: 'stderr',
        line: `[qa-agent] ⚠ Native app path detected (${rawTarget}). Playwright cannot run .apk/.ipa/.app — this needs Appium integration. Skipping BASE_URL override.`,
      });
    } else if (!/^https?:\/\//i.test(rawTarget)) {
      sse(res, 'log', {
        stream: 'stderr',
        line: `[qa-agent] ⚠ Target "${rawTarget}" is not an http(s) URL and isn't a recognised app path. Skipping BASE_URL override.`,
      });
    } else {
      spawnEnv.BASE_URL = rawTarget;
      sse(res, 'log', {
        stream: 'stdout',
        line: `[qa-agent] BASE_URL set to ${rawTarget}${isMobile ? ' (mobile web context)' : ''}`,
      });
    }
  }

  let child: ChildProcessWithoutNullStreams;
  try {
    child = spawn(command, {
      cwd: FRAMEWORK_ROOT,
      env: spawnEnv,
      stdio: ['ignore', 'pipe', 'pipe'],
      shell: true,
    }) as ChildProcessWithoutNullStreams;
  } catch (err: any) {
    sse(res, 'error', {
      message: 'Failed to spawn Playwright: ' + err.message,
    });
    sse(res, 'done', { ok: false, elapsedSec: 0 });
    res.end();
    return;
  }

  const timeout = setTimeout(() => {
    sse(res, 'log', {
      stream: 'stderr',
      line: `[qa-agent] Timeout after ${timeoutSec}s — killing Playwright process.`,
    });
    child.kill('SIGKILL');
  }, timeoutSec * 1000);

  const tcResults: Array<{ scenario: string; tcId?: string; status: string }> =
    [];

  child.stdout.on('data', (buf: Buffer) => {
    const lines = buf.toString().split('\n');
    for (const line of lines) {
      if (!line) continue;
      sse(res, 'log', { stream: 'stdout', line });
      const p = parseProgressLine(line);
      if (p?.scenario && p?.status) {
        tcResults.push({
          scenario: p.scenario,
          tcId: p.tcId,
          status: p.status,
        });
        sse(res, 'progress', p);
      }
    }
  });

  child.stderr.on('data', (buf: Buffer) => {
    const lines = buf.toString().split('\n');
    for (const line of lines) {
      if (line) sse(res, 'log', { stream: 'stderr', line });
    }
  });

  child.on('close', (code) => {
    clearTimeout(timeout);
    const elapsedSec = Math.round((Date.now() - t0) / 100) / 10;
    const passed = tcResults.filter((r) => r.status === 'pass').length;
    const failed = tcResults.filter((r) => r.status === 'fail').length;
    const reportPath = path.join(
      FRAMEWORK_ROOT,
      'playwright-report',
      'index.html',
    );

    sse(res, 'result', {
      ticketId: body.ticketId,
      passed,
      failed,
      exitCode: code,
      reportPath,
      tcResults,
    });
    sse(res, 'done', { ok: code === 0, elapsedSec });
    res.end();
  });

  // If the client disconnects (closes browser / aborts), kill the child.
  req.on('close', () => {
    if (!child.killed) child.kill('SIGTERM');
  });
});

/**
 * GET /automation/generated
 * List the generated feature and steps files so the frontend can show "you have
 * N unimplemented step files" hints.
 */
automationRouter.get('/generated', (_req, res) => {
  const features = fs.existsSync(FEATURES_DIR)
    ? fs.readdirSync(FEATURES_DIR).filter((f) => f.endsWith('.feature'))
    : [];
  const steps = fs.existsSync(STEPS_DIR)
    ? fs.readdirSync(STEPS_DIR).filter((f) => f.endsWith('.steps.ts'))
    : [];
  res.json({ features, steps });
});
